research_task:
  description: >

    <conversation_list> {history} </conversation_list>
    <instructions> 
    Understand the context and answer these questions:
    
    1. What is the most recent message in context intents? Please explain why do you think so?
    2. Is conversation or most recent message speaking English or Tagalog or Taglish? Please explain what makes you 
    think they use that language?
    3. Is user using unknown or incomprehensible words that could be considered slang, generation-Z word, 
    dialects or probably names or expressions? Please explain what do you understand in conversation list context 
    if such words identified like that.
    4. For initial assessment, What do you think is the user talking about and your understanding based on context?
    Explain it and dont limit your findings but a maximum of 10 sentences can be done only. A minimum of 1 sentence 
    for a very easy task like English conversation.
    5. Summary of the previous context for better contextual understanding and not hallucinate.
    </instructions>
  expected_output: >
    Answer the list and reference it to the conversation list each number should be answered in detailed and 
    concise answers.
  agent: researcher

reporting_task:
  description: >
    Using the context and the [conversation_history : {history} ], transform all context into conversational answer.
    Answer should be in a language either one or multiple language in one sentence. If it is tagalog, then reply in 
    tagalog, if it is English, reply in English. If it is Taglish, reply or mirror but the important thing is replying
    in Tagalog with some english words that can be used as nouns or an object. Be creative in text sentence but dont 
    add unnecessary topics or long explanations
  expected_output: >
    Answer with the context and make it conversational text like how chatbot reply to customers. 
    Use the previous conversation [ context : {history}] as supporting information as context
  agent: reporting_analyst
